version: '2.4'

services:
  dev:
    build:
      context: .
    image: birkand/remote_retro_dev
    ports: 
      - "4000:4000"
      - "5001:5001"
    depends_on: 
      - "db"
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "--", "tail", "-f", "/dev/null"]
    environment:
      - RETRO_DB_HOST=db
      - REMOTE_RETRO_GOOGLE_OAUTH_CLIENT_ID
      - REMOTE_RETRO_GOOGLE_OAUTH_CLIENT_SECRET
      - REMOTE_RETRO_GOOGLE_OAUTH_REDIRECT_URI
    volumes:
      - ".:/app"

  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=remote_retro_dev
